.TH "src/headers Directory Reference" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdb\&.h\fP"
.br
.ti -1c
.RI "file \fBedit\&.h\fP"
.br
.ti -1c
.RI "file \fBinterface\&.h\fP"
.br
.ti -1c
.RI "file \fBlogin\&.h\fP"
.br
.ti -1c
.RI "file \fBregister\&.h\fP"
.br
.ti -1c
.RI "file \fBuserstruct\&.h\fP"
.br
.in -1c
