.TH "src/lib/users Directory Reference" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib/users Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlogin\&.c\fP"
.br
.ti -1c
.RI "file \fBregister\&.c\fP"
.br
.in -1c
