.TH "src/headers/addproducts.h" 3 "Sun Nov 29 2020" "Version v01" "CS5101-MidSem Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/addproducts.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBaddProducts\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void addProducts ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-MidSem Project from the source code\&.
