.TH "src/headers/colors.h" 3 "Sun Nov 29 2020" "Version v01" "CS5101-MidSem Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/colors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBANSI_COLOR_RED\fP   '\\x1b[31m'"
.br
.ti -1c
.RI "#define \fBANSI_COLOR_GREEN\fP   '\\x1b[32m'"
.br
.ti -1c
.RI "#define \fBANSI_COLOR_YELLOW\fP   '\\x1b[33m'"
.br
.ti -1c
.RI "#define \fBANSI_COLOR_BLUE\fP   '\\x1b[34m'"
.br
.ti -1c
.RI "#define \fBANSI_COLOR_MAGENTA\fP   '\\x1b[35m'"
.br
.ti -1c
.RI "#define \fBANSI_COLOR_CYAN\fP   '\\x1b[36m'"
.br
.ti -1c
.RI "#define \fBANSI_COLOR_RESET\fP   '\\x1b[0m'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANSI_COLOR_BLUE   '\\x1b[34m'"

.PP
Definition at line 7 of file colors\&.h\&.
.SS "#define ANSI_COLOR_CYAN   '\\x1b[36m'"

.PP
Definition at line 9 of file colors\&.h\&.
.SS "#define ANSI_COLOR_GREEN   '\\x1b[32m'"

.PP
Definition at line 5 of file colors\&.h\&.
.SS "#define ANSI_COLOR_MAGENTA   '\\x1b[35m'"

.PP
Definition at line 8 of file colors\&.h\&.
.SS "#define ANSI_COLOR_RED   '\\x1b[31m'"

.PP
Definition at line 4 of file colors\&.h\&.
.SS "#define ANSI_COLOR_RESET   '\\x1b[0m'"

.PP
Definition at line 10 of file colors\&.h\&.
.SS "#define ANSI_COLOR_YELLOW   '\\x1b[33m'"

.PP
Definition at line 6 of file colors\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-MidSem Project from the source code\&.
