.TH "contributors" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contributors \- Group Members 

.SH "Niku Nitin"
.PP
.SS "Email ID: nn16ms077@iiserkol\&.ac\&.in"
.SS "Roll No: 16MS077"
\fBNiku Nitin\fP has authored following functions/files of the application: 
.br
 \fBreadusers()\fP | \fBreadproducts()\fP | \fBwriteusers()\fP | \fBwriteproducts()\fP | \fBusersdata()\fP | \fBproductsdata()\fP | \fBgetid()\fP 
.PP
.SH "Rahul Pratap Singh"
.PP
.SS "Email ID: rps16ms064@iiserkol\&.ac\&.in"
.SS "Roll No: 16MS064"
\fBRahul Pratap Singh\fP has authored following functions/files of the application: 
.br
 \fBsearchproducts()\fP | \fBtoLower()\fP | \fBlogin()\fP | \fBregi()\fP 
.PP
.SH "Akash Kumar Nigam"
.PP
.SS "Email ID: akn16ms147@iiserkol\&.ac\&.in"
.SS "Roll No: 16MS147"
\fBAkash Kumar Nigam\fP has authored following functions/files of the application: 
.br
 \fBynprompt()\fP | \fBusers\fP | \fBproducts\fP | \fBreset_productsid_arr()\fP | \fBlogout()\fP | \fBmain\&.c\fP 
.PP
.SH "Rohit Prasad"
.PP
.SS "Email ID: rp16ms176@iiserkol\&.ac\&.in"
.SS "Roll No: 16MS176"
\fBRohit Prasad\fP has authored following functions/files of the application: 
.br
 \fBwritesession()\fP | \fBreadsession()\fP | \fBwritecart()\fP | \fBreadcart()\fP | \fBheader_interface()\fP | \fBfooter_interface()\fP | \fBmain_interface()\fP | \fBlogin_interface()\fP | \fBregister_interface()\fP | \fBadmin_interface()\fP | \fBuser_interface()\fP | \fBcart_interface()\fP | \fBbill_interface()\fP | \fBproduct_search_result_interface()\fP | \fBedit_product_interface()\fP 
