.TH "data" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data \- Dummy Data 

.SH "User Data"
.PP
.PD 0
.IP "\(bu" 2

.PP
.SS "Admin"
.PD 0
.IP "\(bu" 2
\fBFirst Name\fP - Niku 
.IP "\(bu" 2
\fBLast Name\fP - Nitin 
.IP "\(bu" 2
\fBUsername\fP - nick 
.IP "\(bu" 2
\fBPassword\fP - nick 
.PP
.SS "Customer"
.PD 0
.IP "\(bu" 2
\fBFirst Name\fP - Nitin 
.IP "\(bu" 2
\fBLast Name\fP - Niku 
.IP "\(bu" 2
\fBUsername\fP - nitin 
.IP "\(bu" 2
\fBPassword\fP - nitin 
.PP
.SS "Customer"
.PD 0
.IP "\(bu" 2
\fBFirst Name\fP - Rahul 
.IP "\(bu" 2
\fBLast Name\fP - Pratap 
.IP "\(bu" 2
\fBUsername\fP - rahul 
.IP "\(bu" 2
\fBPassword\fP - rahul 
.PP
.SS "Customer"
.PD 0
.IP "\(bu" 2
\fBFirst Name\fP - Rohit 
.IP "\(bu" 2
\fBLast Name\fP - Prasad 
.IP "\(bu" 2
\fBUsername\fP - rohit 
.IP "\(bu" 2
\fBPassword\fP - rohit 
.PP
.SS "Customer"
.PD 0
.IP "\(bu" 2
\fBFirst Name\fP - Akash 
.IP "\(bu" 2
\fBLast Name\fP - Nigam 
.IP "\(bu" 2
\fBUsername\fP - akash 
.IP "\(bu" 2
\fBPassword\fP - akash 
.PP
.SH "Product Data"
.PP
.PD 0
.IP "\(bu" 2

.PP
.SS "Product1"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Riding Jacket 
.IP "\(bu" 2
\fBCategory\fP - Automotive essentials 
.IP "\(bu" 2
\fBSeller\fP - ETraders 
.IP "\(bu" 2
\fBPrice\fP - 4500 
.IP "\(bu" 2
\fBStock\fP - 200 
.PP
.SS "Product2"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Studds Helmet Black 
.IP "\(bu" 2
\fBCategory\fP - Automotive essentials 
.IP "\(bu" 2
\fBSeller\fP - RS Wholesalers 
.IP "\(bu" 2
\fBPrice\fP - 600 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product3"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Shower Curtain 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 299 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product4"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Wax Tealight Candles 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 299 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product5"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - 12-inch Wall Clock 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 629 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product6"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Collage Photo Frames 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 629 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product7"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Plastic Clothes Hanger 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 629 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product8"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Foldable Step Ladder 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 1699 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product9"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Blankets 
.IP "\(bu" 2
\fBCategory\fP - Home essentials 
.IP "\(bu" 2
\fBSeller\fP - Cloudtail India 
.IP "\(bu" 2
\fBPrice\fP - 1699 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP
.SS "Product10"
.PD 0
.IP "\(bu" 2
\fBProduct Name\fP - Tubeless Scooter Tyre 
.IP "\(bu" 2
\fBCategory\fP - Automotive essentials 
.IP "\(bu" 2
\fBSeller\fP - RS Wholesalers 
.IP "\(bu" 2
\fBPrice\fP - 1149 
.IP "\(bu" 2
\fBStock\fP - 100 
.PP

