.TH "src/main.c" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'headers/register\&.h'\fP
.br
\fC#include 'headers/login\&.h'\fP
.br
\fC#include 'headers/db\&.h'\fP
.br
\fC#include 'headers/interface\&.h'\fP
.br
\fC#include 'headers/userstruct\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBreset_productsid_arr\fP (int *ptr, int size)"
.br
.ti -1c
.RI "void \fBlogout\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void logout ()"

.PP
Definition at line 214 of file main\&.c\&.
.SS "int main (void)"

.PP
Definition at line 19 of file main\&.c\&.
.SS "int reset_productsid_arr (int * ptr, int size)"

.PP
Definition at line 203 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-Mid Semester Project from the source code\&.
