.TH "products" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
products \- Authored By: @contributorsakash\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <userstruct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "id of the product "
.ti -1c
.RI "char \fBpname\fP [150]"
.br
.RI "Product Name\&. "
.ti -1c
.RI "char \fBcategory\fP [120]"
.br
.RI "Category for the product\&. "
.ti -1c
.RI "char \fBseller\fP [100]"
.br
.RI "Seller of the product\&. "
.ti -1c
.RI "float \fBprice\fP"
.br
.RI "Selling Price of the product\&. "
.ti -1c
.RI "int \fBstock\fP"
.br
.RI "Number of products in stock\&. "
.ti -1c
.RI "int \fBstatus\fP"
.br
.RI "Status i\&.e\&. Active=1 or Deleted=0\&. "
.in -1c
.SH "Detailed Description"
.PP 
Authored By: @contributorsakash\&. 

Structure data for all products 
.PP
Definition at line 30 of file userstruct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char category[120]"

.PP
Category for the product\&. 
.PP
Definition at line 37 of file userstruct\&.h\&.
.SS "int id"

.PP
id of the product 
.PP
Definition at line 33 of file userstruct\&.h\&.
.SS "char pname[150]"

.PP
Product Name\&. 
.PP
Definition at line 35 of file userstruct\&.h\&.
.SS "float price"

.PP
Selling Price of the product\&. 
.PP
Definition at line 41 of file userstruct\&.h\&.
.SS "char seller[100]"

.PP
Seller of the product\&. 
.PP
Definition at line 39 of file userstruct\&.h\&.
.SS "int status"

.PP
Status i\&.e\&. Active=1 or Deleted=0\&. 
.PP
Definition at line 45 of file userstruct\&.h\&.
.SS "int stock"

.PP
Number of products in stock\&. 
.PP
Definition at line 43 of file userstruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-Mid Semester Project from the source code\&.
