.TH "src/headers/register.h" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/register.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBregi\fP (char fname[], char lname[], char username[], char password[])"
.br
.RI "Authored By: Rahul Pratap Singh\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int regi (char fname[], char lname[], char username[], char password[])"

.PP
Authored By: Rahul Pratap Singh\&. This function adds a new user to the database and automatically granting access to application\&. 
.PP
\fBParameters\fP
.RS 4
\fIfname\fP First Name of the user 
.br
\fIlname\fP Last Name of the user 
.br
\fIusername\fP Uniques username for the registration 
.br
\fIpassword\fP A strong pasword that can be later used for logging in application 
.RE
.PP
\fBReturns\fP
.RS 4
Returns an integer i\&.e\&. 0 or 1\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBusers\fP \fBgetid()\fP \fBwriteusers()\fP 
.RE
.PP
\fBAttention\fP
.RS 4
This function cannot be used for registering an Admin\&. Admin credentials are hard coded in the source file\&. 
.RE
.PP

.PP
Definition at line 7 of file register\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-Mid Semester Project from the source code\&.
