.TH "users" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
users \- Authored By: @contributorsakash\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <userstruct\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "id of the user "
.ti -1c
.RI "char \fBfname\fP [20]"
.br
.RI "First Name of the user\&. "
.ti -1c
.RI "char \fBlname\fP [20]"
.br
.RI "Last Name of the user\&. "
.ti -1c
.RI "char \fBusername\fP [10]"
.br
.RI "Unique username of the user\&. "
.ti -1c
.RI "char \fBpassword\fP [20]"
.br
.RI "Password matching to a uniques username\&. "
.ti -1c
.RI "char \fBrole\fP [8]"
.br
.RI "Role of the user i\&.e\&. Customer or Admin\&. "
.ti -1c
.RI "int \fBstatus\fP"
.br
.RI "Status i\&.e\&. Active account=1 or Deleted account=0\&. "
.in -1c
.SH "Detailed Description"
.PP 
Authored By: @contributorsakash\&. 

Structure data for all users 
.PP
Definition at line 8 of file userstruct\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char fname[20]"

.PP
First Name of the user\&. 
.PP
Definition at line 13 of file userstruct\&.h\&.
.SS "int id"

.PP
id of the user 
.PP
Definition at line 11 of file userstruct\&.h\&.
.SS "char lname[20]"

.PP
Last Name of the user\&. 
.PP
Definition at line 15 of file userstruct\&.h\&.
.SS "char password[20]"

.PP
Password matching to a uniques username\&. 
.PP
Definition at line 19 of file userstruct\&.h\&.
.SS "char role[8]"

.PP
Role of the user i\&.e\&. Customer or Admin\&. 
.PP
Definition at line 21 of file userstruct\&.h\&.
.SS "int status"

.PP
Status i\&.e\&. Active account=1 or Deleted account=0\&. 
.PP
Definition at line 23 of file userstruct\&.h\&.
.SS "char username[10]"

.PP
Unique username of the user\&. 
.PP
Definition at line 17 of file userstruct\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-Mid Semester Project from the source code\&.
