.TH "src/headers/userstruct.h" 3 "Sun Nov 29 2020" "Version v1.0" "CS5101-Mid Semester Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/userstruct.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBusers\fP"
.br
.RI "Authored By: @contributorsakash\&. "
.ti -1c
.RI "struct \fBproducts\fP"
.br
.RI "Authored By: @contributorsakash\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS5101-Mid Semester Project from the source code\&.
